namespace DBEnum
{
    public enum BUILDING
    {
        TRADE_GOODS = 0,
        HOUSING = 1,
        FORTRESS = 2,
        BARRACKS = 3,
        ARMORY = 4,
        FIGHTERS_GUILD = 5,
        ARMORERS_GUILD = 6,
        WAR_COLLEGE = 7,
        SMITHY = 8,
        STABLES = 9,
        ANIMISTS_GUILD = 10,
        FANTASTIC_STABLES = 11,
        SHIPWRIGHTS_GUILD = 12,
        SHIP_YARD = 13,
        MARITIME_GUILD = 14,
        SAWMILL = 15,
        LIBRARY = 16,
        SAGES_GUILD = 17,
        ALCHEMISTS_GUILD = 18,
        UNIVERSITY = 19,
        ORACLE = 20,
        WIZARDS_GUILD = 21,
        SHRINE = 22,
        TEMPLE = 23,
        PARTHENON = 24,
        CATHEDRAL = 25,
        MARKETPLACE = 26,
        BANK = 27,
        MERCHANTS_GUILD = 28,
        GRANARY = 29,
        FARMERS_MARKET = 30,
        FORESTERS_GUILD = 31,
        BUILDERS_HALL = 32,
        MINERS_GUILD = 33,
        DWARF_MINERS_GUILD = 34,
        MECHANICIANS_GUILD = 35,
        CITY_WALLS = 36,
        ASTRAL_GATE = 37,
        EARTH_GATE = 38,
        NATURES_EYE = 39,
        ALTAR_OF_BATTLE = 40,
        STREAM_OF_LIFE = 41,
        MAGIC_COLLECTOR = 42,
        SOUL_MECHANICIANS_GUILD = 43,
        SOUL_SHIPWRIGHTS_GUILD = 44,
        TECH_STABLES = 45,
        BLUEORCS_GHOST_SHIPYARD = 46,
        FISHERMAN_HUT = 47,
        BLUEORCS_RAIDERS_HUT = 48,
        BLUEORCS_INDENTURED_WORKERS_GUILD = 49
    }
}
