namespace DBEnum
{
    public enum LOCATION
    {
        WEAK_LAIR = 0,
        LAIR = 1,
        STRONG_LAIR = 2,
        WEAK_CAVE = 3,
        CAVE = 4,
        STRONG_CAVE = 5,
        WEAK_KEEP = 6,
        KEEP = 7,
        STRONG_KEEP = 8,
        WEAK_ANCIENT_TEMPLE = 9,
        ANCIENT_TEMPLE = 10,
        STRONG_ANCIENT_TEMPLE = 11,
        WEAK_FALLEN_TEMPLE = 12,
        FALLEN_TEMPLE = 13,
        STRONG_FALLEN_TEMPLE = 14,
        WEAK_DUNGEON = 15,
        DUNGEON = 16,
        STRONG_DUNGEON = 17,
        RUINS = 18,
        NATURE_TOWER = 19,
        CHAOS_TOWER = 20,
        DEATH_TOWER = 21,
        SORCERY_TOWER = 22,
        LIFE_TOWER = 23,
        SYNERGY_TOWER = 24,
        BANDIT_LAIR = 25,
        MONSTER_LAIR_DRAGON = 26,
        MONSTER_LAIR_BEAST = 27,
        ARENA = 28,
        OLD_TEMPLE = 29,
        SECRET_ELF_LANDS = 30,
        HALFLING_BUILDING = 31,
        TRIBAL_VILLAGE = 32,
        KLACKON_HIVE = 33,
        ORC_CAMP = 34,
        TECH_DUNGEON = 35,
        WEAK_WATER_WIND_CAVE = 36,
        WATER_WIND_CAVE = 37,
        STRONG_WATER_WIND_CAVE = 38,
        WEAK_WATER_REEF_TREASURE_ISLAND = 39,
        WATER_REEF_TREASURE_ISLAND = 40,
        STRONG_WATER_REEF_TREASURE_ISLAND = 41,
        WATER_BOSS_LAIR_1 = 42,
        WATER_BOSS_LAIR_2 = 43
    }
}
