namespace DBEnum
{
    public enum TRAIT
    {
        ALCHEMY = 0,
        ARCHMAGE = 1,
        ARTIFICER = 2,
        CHANNELER = 3,
        CHAOS_MASTERY = 4,
        CHARISMATIC = 5,
        CONJURER = 6,
        DIVINE_POWER = 7,
        FAMOUS = 8,
        INFERNAL_POWER = 9,
        MANA_FOCUSING = 10,
        MYRRAN = 11,
        NATURE_MASTERY = 12,
        NODE_MASTERY = 13,
        RUNEMASTER = 14,
        SAGE_MASTERY = 15,
        SORCERY_MASTERY = 16,
        WARLORD = 17,
        FANTASTIC_WARLORD = 18,
        STONEMASON = 19,
        LIFEBRINGER = 20,
        HERO_MAGNET = 21,
        NATURE_SUMMONER = 22,
        TECHMASTER = 23,
        DEMONOLOGIST = 24,
        MYRRAN_REFUGEE = 25,
        IMPROVED_WARLORD = 26,
        ANTI_MAGIC = 27,
        ORCOMANCER = 28,
        NECROMANCER = 29,
        DEATH_EATER = 30,
        KLACKON_SUPREMACY = 31,
        SWIFT_SEALEGS = 32,
        POWER_PEOPLE = 33,
        THE_PIRATE = 34,
        TACTITIAN = 35,
        SEA_HUNTER = 36,
        WATER_BOSS_1 = 37,
        WATER_BOSS_2 = 38
    }
}
