namespace DBDef
{
    public enum EEnchantmentType
    {
        None = 0,
        GoldModifier = 1,
        GoldModifierMP = 2,
        FoodModifier = 3,
        FoodModifierMP = 4,
        ManaModifier = 5,
        ManaModifierMP = 6,
        PowerModifier = 7,
        PowerModifierMP = 8,
        PowerModifierReligious = 9,
        PowerModifierNode = 10,
        ResearchModifier = 11,
        ProductionModifier = 12,
        ProductionModifierMP = 13,
        PopulationGrowModifier = 14,
        PopulationGrowModifierMP = 15,
        UnitHealModifier = 16,
        NewUnitXpModifier = 17,
        NewUnitModifier = 18,
        UnrestModifier = 19,
        UnrestModifierMP = 20,
        RebelsModifier = 21,
        VisibilityRangeModifier = 22,
        MaximumPopulationModifier = 23,
        MaximumPopulationModifierMP = 24,
        EndTurnEffect = 25,
        EndTurnPositiveDispelEffect = 26,
        EndTurnNegativeDispelEffect = 27,
        EndTurnNeutralTownIncludedEffect = 28,
        WizardVisibilityModifier = 29,
        AttributeChange = 30,
        AttributeChangeMP = 31,
        RemoteUnitAttributeChange = 32,
        RemoteUnitAttributeChangeMP = 33,
        BattleTurnStartEffect = 34,
        BattleTurnEndEffect = 35,
        BattleStartEffect = 36,
        BattleEndEffect = 37,
        BattleWizardTowerEffect = 38,
        WizardOrGlobalToTownEnchantment = 39,
        GroupChange = 40
    }
}
